
#ifndef CHERRYUSB_CLI_USB_CONFIG_H
#define CHERRYUSB_CLI_USB_CONFIG_H

#include "cherryusb_config_template.h"

#undef CONFIG_USBDEV_TEST_MODE
#define CONFIG_USBDEV_TEST_MODE

#undef CONFIG_USBDEV_MSC_MAX_BUFSIZE
#define CONFIG_USBDEV_MSC_MAX_BUFSIZE 1024

#undef CONFIG_USBDEV_MSC_THREAD
#define CONFIG_USBDEV_MSC_THREAD

#undef CONFIG_USBDEV_MSC_PRIO
#define CONFIG_USBDEV_MSC_PRIO 15

#undef CONFIG_USBHOST_MAX_SERIAL_CLASS
#define CONFIG_USBHOST_MAX_SERIAL_CLASS 2

#undef CONFIG_USBHOST_MAX_HID_CLASS
#define CONFIG_USBHOST_MAX_HID_CLASS 2

#undef CONFIG_USBHOST_MAX_MSC_CLASS
#define CONFIG_USBHOST_MAX_MSC_CLASS 1

#undef CONFIG_USBHOST_PSC_PRIO
#define CONFIG_USBHOST_PSC_PRIO 5

#undef CONFIG_USBHOST_REQUEST_BUFFER_LEN
#define CONFIG_USBHOST_REQUEST_BUFFER_LEN 2048

#undef CONFIG_USB_EHCI_ITD_NUM
#define CONFIG_USB_EHCI_ITD_NUM 20

#undef CONFIG_USB_HS
#ifndef BL702
#define CONFIG_USB_HS
#endif

#endif /* CHERRYUSB_CLI_USB_CONFIG_H */
